### ISSUE TITLE
Channel name for publish and subscribe methods

### ISSUE THREAD

**Issue by sohanmaheshwar** [shyampurk/HomeConv#1]
Hello.

More of a question than an issue, but in the pub_subscribe you've mentioned the channel name as 'smarthome_response' and in the pub_publish the channel name is 'smarthome_request'. 

Does this mean that there are two different BLOCKS? Or multiple channels for the same BLOCK? This wasn't clear in the Readme file.

Thanks!

**Comment by shyampurk** [comment]
Hi

Its the same BLOCK and two channels operating on it. 

-Shyam
