### ISSUE TITLE
Import conversation workspace. 

### ISSUE THREAD

**Issue by craigkj312** [shyampurk/HomeConv#2]
It's possible to export a JSON document of a workspace for easy import. 

<img width="167" alt="Download Button" src="https://cloud.githubusercontent.com/assets/5383898/25457621/7da52616-2a9c-11e7-8646-8ec8f0512608.png">

It would be much easier for a user to import your pre-created workspace instead of following along with the current README. 

See: https://github.com/watson-developer-cloud/conversation-simple

They handle the conversation setup in a simple manner that lets the developer get right back into the code.

If you specifically ignored this feature of conversation for some reason, feel free to just close this issue.

**Comment by shyampurk** [comment]
Thanks a lot for this suggestion. I wasn't aware of it.

Will give it a try for the future projects.

-Shyam
